### ISSUE TITLE
Database Prepopulation

### ISSUE THREAD

**Issue by zeinabfarag-zz** [RobWawrzak/GroupProject#10]
A page will be created to pre-populate the app with group purchase options. There should be an API call to a site like AliBaba to draw down approximately 10 product offerings, including images, names, prices and desired quantities. The information will then be consumed by the landing page to lure in new and existing users in order to either sign up or make a commitment.

**Comment by iamdp** [comment]
Still waiting on Alibaba API key to be issued. No suitable alternatives. Instead populated database manually with records.
